credentials:
  usernames:
    alice:
      email: alice@company.com
      name: Alice
      password: hashed_password_here
      role: finance
    bob:
      email: bob@company.com
      name: Bob
      password: hashed_password_here
      role: logistics
    carol:
      email: carol@company.com
      name: Carol
      password: hashed_password_here
      role: operations
    dave:
      email: dave@company.com
      name: Dave
      password: hashed_password_here
      role: hr

cookie:
  name: session_cookie
  key: secret_key
  expiry_days: 1

preauthorized:
  emails:
    - admin@company.com
